### ISSUE TITLE
.packages/create-awesome-node-app/index.js my-app not working

### ISSUE THREAD

**Issue by VoidVampire** [Create-Node-App/create-node-app#32]
### Describe the bug

https://github.com/Create-Node-App/create-node-app#running-locally
I am having issue running the last command on Fedora 38 which is : .packages/create-awesome-node-app/index.js my-app

### Expected Behavior

it should start creating node app

### Current Behavior

getting error

### Reproduction Steps

https://github.com/Create-Node-App/create-node-app#running-locally

### Additional Information/Context

![image](https://github.com/Create-Node-App/create-node-app/assets/80760499/8e40b663-6df2-42f0-9fe7-190c635316a8)

### Version used

latest of everything except node since it used v18

### Environment details (OS name and version, etc.)

Fedora 38

**Comment by ulises-jeremias** [comment]
@VoidVampire hey! thanks for opening this issue 😊 

quick questions to understand the error:

- what happens if you run it again? 👀 
- what happens if you run the command in a fresh installation? doing the following:

```sh
cd /tmp
fnm use 18
npm i -g create-awesome-node-app@latest
create-awesome-node-app my-app
```

**Comment by ulises-jeremias** [comment]
@VoidVampire here you can update the code locally to print the error you are getting https://github.com/Create-Node-App/create-node-app/blob/0599b049098660320827f94d033ece71255ba873/packages/create-awesome-node-app/src/templates.ts#L47

you will need to build the code again before giving it a try

**Comment by VoidVampire** [comment]
I rebuilded and console logged "Error ->>>>>>>>>>" and the error itself: https://codeshare.io/createnodeappissue

**Comment by ulises-jeremias** [comment]
@VoidVampire seems to be a timeout error. Can you try doing a curl to that endpoint?

```sh
curl https://raw.githubusercontent.com/nanlabs/frontend-reference/main/examples.json
```

**Comment by VoidVampire** [comment]
Getting this error even after restarting laptop

`curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 134599 ms: Couldn't connect to server`

![image](https://github.com/Create-Node-App/create-node-app/assets/80760499/c8c9d6b3-dfd2-4a94-96db-a94e92c14786)

**Comment by ulises-jeremias** [comment]
oh ok, that means you are having problems trying to fetch stuff from github 🤔 it could be a networking issue or something else. Not sure how exactly I can help on that. Can you send me the output of `create-awesome-node-app --info`?

**Comment by VoidVampire** [comment]
`Environment Info:

  System:
    OS: Linux 6.5 Fedora Linux 38 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 13.36 GB / 15.33 GB
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.14.2 - /run/user/1000/fnm_multishells/3059_1696261769735/bin/node
    Yarn: Not Found
    npm: 9.5.0 - /run/user/1000/fnm_multishells/3059_1696261769735/bin/npm
    pnpm: Not Found
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
`

**Comment by ulises-jeremias** [comment]
#### Possible Solutions:

1. **Network Connectivity:**
   - Ensure you have an active network connection.
   - Verify if you can access other websites from your machine.

2. **Firewall:**
   - Check if there's a firewall that might be blocking the connection. Temporarily disable the firewall to test.

3. **Proxy:**
   - If behind a proxy, ensure the proxy configuration is correct. You can set the proxy for `curl` using the `http_proxy` and `https_proxy` environment variables.

      ```bash
      export http_proxy=http://proxy_name:port
      export https_proxy=http://proxy_name:port
      ```

4. **DNS:**
   - Ensure your system can resolve the domain name `raw.githubusercontent.com` correctly. Try a separate DNS query to verify.

      ```bash
      nslookup raw.githubusercontent.com
      ```

5. **Long Timeout:**
   - In some cases, the network might be congested or have temporary issues. Retry the `curl` command after some time.

6. **Change DNS Server:**
   - Try changing your DNS configuration to use a different public DNS server, such as Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1).

      ```bash
      sudo nano /etc/resolv.conf
      ```

      Add or modify lines to use a different DNS server:

      ```bash
      nameserver 8.8.8.8
      nameserver 8.8.4.4
      ```

      Save the changes and try again.

After performing these checks, you should be able to determine the cause of the issue and take appropriate actions. If the problem persists, consider seeking help on Fedora or GitHub support forums, as it may be specific to your environment or configuration.

**Comment by ulises-jeremias** [comment]
@VoidVampire let me know if there is something else I can do to help!

**Comment by VoidVampire** [comment]
@ulises-jeremias Hi, so adding 8.8.8.8 to dns sovled the issue, thanks for it. Also, I apologise it's been just few weeks since I have started using linux (fedora) and I never had this issue on windows so I couldn't figure out this on my own. 

So this issue is resolved.

Btw I just want to test me skills in #25 but I can't find the files where the logic for using package managers (yarn or npm) is :sweat:. Can you please point it out :sweat_smile: ?

**Comment by VoidVampire** [comment]
Since this issue is solved, I will close the issue with this comment and put my other issues elsewhere
