### ISSUE TITLE
Failed to fetch template data

### ISSUE THREAD

**Issue by JianJroh** [Create-Node-App/create-node-app#35]
### Describe the bug

Failed to run `pnpm create awesome-node-app` 

### Expected Behavior

It works.

### Current Behavior

Works with npm ,but pnpm dosen't.

### Reproduction Steps

- node v18.16.0
- pnpm 8.10.4

![image](https://github.com/Create-Node-App/create-node-app/assets/45714701/a60482d5-9b89-40c7-823e-0daf72f9d7bd)

### Version used

0.4.20

### Environment details (OS name and version, etc.)

- window 10
- node v18.16.0
- pnpm 8.10.4

**Comment by ulises-jeremias** [comment]
hi @JianJroh thank you for opening this issue! could you paste the output of the following command here? 👀 

```sh
pnpm create awesome-node-app --info
```

**Comment by ulises-jeremias** [comment]
> hi @JianJroh thank you for opening this issue! could you paste the output of the following command here? 👀
> 
> ```shell
> pnpm create awesome-node-app --info
> ```

in case it does not work, you can try

```sh
npm create awesome-node-app@latest --info
```

**Comment by JianJroh** [comment]
> hi @JianJroh thank you for opening this issue! could you paste the output of the following command here? 👀嗨@JianJroh，感谢您打开本期！您可以将以下命令的输出粘贴到此处吗？ 👀
> 
> ```shell
> pnpm create awesome-node-app --info
> ```

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 3.42 GB / 15.37 GB
    Node: 18.16.0 - D:\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - D:\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.EXE
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3570

**Comment by JianJroh** [comment]
> hi @JianJroh thank you for opening this issue! could you paste the output of the following command here? 👀
> 
> ```shell
> pnpm create awesome-node-app --info
> ```

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 3.42 GB / 15.37 GB
    Node: 18.16.0 - D:\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - D:\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.EXE
    Watchman: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3570

**Comment by ulises-jeremias** [comment]
@JianJroh thank you! will try to replicate it on my windows machine!

just to get more context, are you using a workstation provided by a company where you work at or something? wondering if maybe the issue is with a firewall or something like that

**Comment by ulises-jeremias** [comment]
will try to fix that to not depend on that anyways
